// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20240912042327_script")]
    partial class script
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataAccessLayer.entity.VehicleDetail", b =>
                {
                    b.Property<int>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("DriverContactNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FCdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InsuranceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehicleId");

                    b.ToTable("vehicleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
